colors:
  # based off of solarized vivid theme and dracula/dircolors
  # Based on 'dracula' theme
  # (https://draculatheme.com/)
  #
  # The assignment of colors to file types roughly follows `dircolors`

  black:  "fbf1c7"
  red:    "9d0006"
  green:  "79740e"
  yellow: "b57614"
  blue:   "fbf1c7"
  purple: "8f3f71"
  cyan:   "427b58"
  orange: "282828"
  white:  "504945"
  base01: "bdae93"

core:
  normal_text:
    foreground: white

  regular_file:
    foreground: white

  reset_to_normal:
    foreground: orange

  directory:
    foreground: purple

  symlink:
    foreground: cyan

  multi_hard_link: {}

  fifo:
    foreground: yellow
    background: black

  socket:
    foreground: blue
    background: black
    font-style: bold

  door:
    foreground: blue
    background: black
    font-style: bold

  block_device:
    foreground: yellow
    background: black
    font-style: bold

  character_device:
    foreground: yellow
    background: black
    font-style: bold

  broken_symlink:
    foreground: red
    background: black
    font-style: bold

  missing_symlink_target:
    foreground: red
    background: black

  setuid:
    foreground: white
    background: red

  setgid:
    foreground: black
    background: yellow

  file_with_capability: {}

  sticky_other_writable:
    foreground: black
    background: green

  other_writable:
    foreground: purple
    background: green

  sticky:
    foreground: white
    background: purple

  executable_file:
    foreground: green

text:
  special:
    foreground: orange

  todo:
    foreground: orange
    font-style: bold

  licenses:
    foreground: orange

  configuration:
    foreground: orange

  other:
    foreground: orange

markup:
  foreground: orange

programming:
  foreground: orange

media:
  image:
    foreground: blue

  audio:
    foreground: cyan

  video:
    foreground: orange
    font-style: bold

  fonts:
    foreground: orange

  3d:
    foreground: blue

office:
  foreground: orange

archives:
  foreground: red
  font-style: bold

executable:
  foreground: green

unimportant:
  foreground: base01
